import Foundation

struct MockData {
    static let sampleProducts: [Product] = [
        Product(
            id: 1,
            name: "Classic White Button Down",
            price: 89.99,
            originalPrice: 129.99,
            brand: "ZARA",
            color: "White",
            availableColors: ["White", "Light Blue", "Black"],
            category: .clothing,
            subcategory: "tops",
            imageURL: "https://images.unsplash.com/photo-1594633313593-bab3825d0caf?w=400",
            images: nil,
            rating: 4.6,
            reviews: 234,
            sizes: ["XS", "S", "M", "L", "XL"],
            material: "Cotton Blend",
            isNew: true,
            onSale: true
        ),
        Product(
            id: 2,
            name: "High-Waisted Jeans",
            price: 129.99,
            originalPrice: nil,
            brand: "H&M",
            color: "Dark Blue",
            availableColors: ["Dark Blue", "Light Blue", "Black"],
            category: .clothing,
            subcategory: "bottoms",
            imageURL: "https://images.unsplash.com/photo-1542272604-787c3835535d?w=400",
            images: nil,
            rating: 4.4,
            reviews: 189,
            sizes: ["24", "25", "26", "27", "28", "29", "30"],
            material: "Denim",
            isNew: false,
            onSale: false
        ),
        Product(
            id: 3,
            name: "Minimalist Throw Pillow",
            price: 45.99,
            originalPrice: nil,
            brand: "West Elm",
            color: "Sage Green",
            availableColors: ["Sage Green", "Dusty Pink", "Cream"],
            category: .decor,
            subcategory: "textiles",
            imageURL: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=400",
            images: nil,
            rating: 4.8,
            reviews: 156,
            sizes: nil,
            material: "Organic Cotton",
            isNew: false,
            onSale: false
        ),
        Product(
            id: 4,
            name: "Vintage Denim Jacket",
            price: 179.99,
            originalPrice: 220.00,
            brand: "UNIQLO",
            color: "Medium Blue",
            availableColors: ["Medium Blue", "Black", "White"],
            category: .clothing,
            subcategory: "outerwear",
            imageURL: "https://images.unsplash.com/photo-1544966503-7cc5ac882d5f?w=400",
            images: nil,
            rating: 4.7,
            reviews: 342,
            sizes: ["XS", "S", "M", "L", "XL", "XXL"],
            material: "100% Cotton Denim",
            isNew: true,
            onSale: true
        ),
        Product(
            id: 5,
            name: "Modern Table Lamp",
            price: 199.99,
            originalPrice: nil,
            brand: "IKEA",
            color: "Brass",
            availableColors: ["Brass", "Black", "White"],
            category: .decor,
            subcategory: "lighting",
            imageURL: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400",
            images: nil,
            rating: 4.5,
            reviews: 98,
            sizes: nil,
            material: "Metal & Fabric",
            isNew: false,
            onSale: false
        ),
        Product(
            id: 6,
            name: "Floral Summer Dress",
            price: 159.99,
            originalPrice: nil,
            brand: "ZARA",
            color: "Floral Print",
            availableColors: ["Floral Print", "Solid Pink", "Solid Yellow"],
            category: .clothing,
            subcategory: "dresses",
            imageURL: "https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=400",
            images: nil,
            rating: 4.3,
            reviews: 267,
            sizes: ["XS", "S", "M", "L", "XL"],
            material: "Viscose Blend",
            isNew: true,
            onSale: false
        )
    ]
    
    static let sampleDesigners: [Designer] = [
        Designer(
            id: 1,
            name: "ZARA",
            description: "Fast fashion retailer known for trendy, affordable clothing that brings runway styles to everyday wardrobes.",
            imageURL: "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=200",
            coverImageURL: "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800",
            specialty: ["Fashion", "Clothing", "Accessories"],
            founded: "1975",
            location: "Spain",
            website: "zara.com",
            social: SocialLinks(instagram: "@zara", twitter: "@zara"),
            featuredIn: ["Vogue", "Harper's Bazaar", "Elle"],
            totalProducts: 15,
            customClothes: CustomClothesInfo(
                available: true,
                startingPrice: 199.0,
                deliveryTime: "3-4 weeks",
                description: "Custom tailored pieces designed by ZARA's in-house designers to your exact specifications.",
                categories: ["Dresses", "Blazers", "Trousers", "Shirts", "Skirts"]
            )
        ),
        Designer(
            id: 2,
            name: "H&M",
            description: "Swedish multinational clothing retailer offering sustainable fashion and conscious choices for the modern consumer.",
            imageURL: "https://images.unsplash.com/photo-1434389677669-e08b4cac3105?w=200",
            coverImageURL: "https://images.unsplash.com/photo-1434389677669-e08b4cac3105?w=800",
            specialty: ["Sustainable Fashion", "Clothing", "Home"],
            founded: "1947",
            location: "Sweden",
            website: "hm.com",
            social: SocialLinks(instagram: "@hm", twitter: "@hm"),
            featuredIn: ["Fashion Week", "Sustainability Awards"],
            totalProducts: 12,
            customClothes: CustomClothesInfo(
                available: true,
                startingPrice: 149.0,
                deliveryTime: "2-3 weeks",
                description: "Sustainable custom clothing made from eco-friendly materials with H&M's conscious design philosophy.",
                categories: ["T-Shirts", "Hoodies", "Jeans", "Jackets", "Dresses"]
            )
        )
    ]
}
